# Generated by Django 2.2.5 on 2023-07-11 17:31

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=50)),
                ('card_cost', models.IntegerField()),
                ('card_class', models.CharField(choices=[('Minion', 'Minion'), ('Spell', 'Spell'), ('Weapon', 'Weapon'), ('Hero', 'Hero'), ('Location', 'Location')], max_length=1)),
                ('card_type', models.CharField(choices=[('Death Knight', 'Death Knight'), ('Demon Hunter', 'Demon Hunter'), ('Druid', 'Druid'), ('Hunter', 'Hunter'), ('Mage', 'Mage'), ('Paladin', 'Paladin'), ('Priest', 'Priest'), ('Rogue', 'Rogue'), ('Shaman', 'Shaman'), ('Warlock', 'Warlock'), ('Warrior', 'Warrior'), ('Neutral', 'Neutral')], max_length=1)),
                ('card_rarity', models.CharField(choices=[('Common', 'Common'), ('Rare', 'Rare'), ('Epic', 'Epic'), ('Legendary', 'Legendary')], max_length=1)),
                ('card_image', models.CharField(max_length=100)),
                ('card_description', models.TextField(max_length=250)),
            ],
            managers=[
                ('Cards', django.db.models.manager.Manager()),
            ],
        ),
    ]
