# Generated by Django 2.2.5 on 2023-07-12 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HSDeckTracker', '0003_auto_20230711_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='card_image',
            new_name='card_image_link',
        ),
    ]
