# Generated by Django 2.2.5 on 2023-07-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HSDeckTracker', '0006_auto_20230717_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_value', models.CharField(max_length=30)),
            ],
        ),
    ]
