# Generated by Django 4.2.3 on 2023-07-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HSDeckTracker', '0007_cardsearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cardsearch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
